### ISSUE TITLE
0.1.2 with Play 2.3 doesn't compile

### ISSUE THREAD

**Issue by drogina** [CedricGatay/play-querydsl#5]
I'm trying to implement the latest version of the plugin in my Play 2.3 application using the instructions provided. I'm using Scala 2.10.4. The com.mysema packages are there, but no Q classes are being generated. 

This is my configuration using 0.1.2:

build.sbt:

```
lazy val root = (project in file(".")).enablePlugins(SbtWeb, PlayScala, QueryDSLPlugin)
```

plugins.sbt:

```
addSbtPlugin("com.code-troopers.play" % "play-querydsl" % "0.1.2")
```

This is the error I'm getting:

```
[error] An annotation processor threw an uncaught exception.
[error] Consult the following stack trace for details.
[error] java.lang.NullPointerException
[error]     at com.mysema.query.codegen.SimpleSerializerConfig.getConfig(SimpleSerializerConfig.java:29)
[error]     at com.mysema.query.apt.DefaultConfiguration.<init>(DefaultConfiguration.java:109)
[error]     at com.mysema.query.apt.jpa.JPAConfiguration.<init>(JPAConfiguration.java:54)
[error]     at com.mysema.query.apt.jpa.JPAAnnotationProcessor.createConfiguration(JPAAnnotationProcessor.java:46)
[error]     at com.mysema.query.apt.AbstractQuerydslProcessor.process(AbstractQuerydslProcessor.java:87)
[error]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
[error]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
[error]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
[error]     at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
[error]     at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
[error]     at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
[error]     at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:439)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:353)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:342)
[error]     at com.sun.tools.javac.main.Main.compile(Main.java:333)
[error]     at com.sun.tools.javac.Main.compile(Main.java:76)
[error]     at com.sun.tools.javac.Main.main(Main.java:61)
```

I am able to generate the Q classes using the 0.1.1 version of the plugin and this configuration in my build.sbt:

```
lazy val root = (project in file(".")).enablePlugins(SbtWeb, PlayScala).configs(QueryDSLPlugin.QueryDSL)

com.typesafe.sbt.SbtNativePackager.projectSettings ++ QueryDSLPlugin.queryDSLSettings
```

**Comment by CedricGatay** [comment]
Do you have classes in your package that should not be enhanced by QueryDSL ?

**Comment by CedricGatay** [comment]
@drogina is the problem still here for you ? I'm closing otherwise.
